Algoritmo "AreaRetangulo"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Obama
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Gabriel Alexsander
// Data atual  : 17/03/2023
Var
Alt, lrg, area: real


Inicio
escreval ("Digite a altura do retangulo:")
leia (alt)
escreval ("digite a largura do retangulo:")
leia (lrg)
area <-alt*lrg
escreva ("area do retangulo é", area)
Fimalgoritmo