Algoritmo "AreaRetangulo"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : jailson
// Descrição   : Calcular a area de um retangulo
// Autor(a)    : Gabriel
// Data atual  : 29/03/2023
Var
   base, altura, area: real

Inicio
   Escreva("Digite a base do retangulo: ")
   Leia(base)
   Escreva("Digite a altura do retangulo: ")
   Leia(altura)
   area <- base * altura
   Escreva("A area do retangulo é: ", area)
FimAlgoritmo