Algoritmo "PositivoNegativo"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : jailson
// Descrição   : Positivo ou Negativo
// Autor(a)    : Gabriel
// Data atual  : 29/03/2023
Var
   valor: Inteiro
Inicio
   Escreval("Digite um valor: ")
   Leia(valor)
   Se valor >= 0 Entao
      Escreval("O valor é positivo")
   Senao
      Escreval("O valor é negativo")
   FimSe
FimAlgoritmo
