Algoritmo "VerificaValorMaior10"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : jailson
// Descrição   : Verifica valor maior que 10
// Autor(a)    : Gabriel
// Data atual  : 29/03/2023
Var
   valor: Inteiro
Inicio
   Escreval("Digite um valor inteiro: ")
   Leia(valor)
   Se valor > 10 Entao
      Escreval("É MAIOR QUE 10!")
   Senao
      Escreval("NÃO É MAIOR QUE 10!")
   FimSe
FimAlgoritmo
